#!/bin/bash
sudo chown -R 'vincent:staff' 0-iam_betty                 10-mirror_permissions       12-directory_permissions  1-who_am_i  3-new_owner  5-execute               7-everybody   9-John_Doe
100-change_owner_and_group  11-directories_permissions  13-change_group           2-groups    4-empty      6-multiple_permissions  8-James_Bond  README.md  
